version: '2'
services:
  els:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    hostname: els
    mem_limit: 1g
    restart: on-failure
    ports:
      - '9200:9200'
      - '9300:9300'
    environment:
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - ES_HEAP_SIZE=512m
      - discovery.type=single-node
      - xpack.security.enabled=false
    networks:
      - web
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    ports:
      - '5601:5601'
    links:
      - els
    environment:
      - ELASTICSEARCH_URL=http://els:9200
    networks:
      - web
  monitoring:
    image: 'samuelebistoletti/docker-statsd-influxdb-grafana:latest'
    ports:
      - '3003:3003'
      - '3004:8083'
      - '8086:8086'
      - '22022:22'
      - '8089:8089/udp'
      - '8125:8125/udp'
    volumes:
      - './grafana:/var/lib/grafana'
    environment:
      - GF_DATABASE_TYPE=sqlite3
    networks:
      - web
  myvault:
    image: vault
    ports:
      - '8200:8200'
    volumes:
      - './vault/database:/vault/file:rw'
      - './vault/config:/vault/config:rw'
      - './vault/bin:/vault/bin'
    cap_add:
      - IPC_LOCK
    command: /vault/bin/start.sh
    networks:
      - web
  rabbitmq:
    image: 'rabbitmq:3-management'
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - web
  postgres:
    image: 'postgres:9.5.9-alpine'
    ports:
      - '5432:5432'
    volumes:
      - './postgres:/data/postgres:rw'
      - './common.sql:/common.sql'
    environment:
      POSTGRES_PASSWORD: qweasdzxc
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
    networks:
      - web
  tracer:
    image: jaegertracing/all-in-one:latest
    depends_on:
      - els
    restart: on-failure
    ports:
      - '16686:16686'
      - '9411:9411'
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://els:9200
      - ES_TAGS_AS_FIELDS=true
    links:
      - els
    networks:
      - web
networks:
  web:
    external: true
